name       : kstars
version    : 17.08.2
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kstars-17.08.2.tar.xz : fe41596cdd9f7b2fe8a2f98d6233ed49ed85c8c49f3ce9e86785ff0d39962bd0
license    : GPL-2.0
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kplotting-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
