name       : kstars
version    : 2.9.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/kstars/kstars-2.9.1.tar.xz : c7fa17f9b367a65d6f50aa063f11f4d358473d74d55fc32c1d67358f3d5e38c4
license    : GPL-2.0
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kplotting-devel
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
