name       : kstars
version    : 3.5.5
release    : 24
source     :
    - https://cdn.download.kde.org/stable/kstars/kstars-3.5.5.tar.xz : 703df56050672af10fc8142296ceaa27134a6a00e8222f3f6677f18ff1ac6b43
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(libraw)
    - pkgconfig(Qt5DataVisualization)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kplotting-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/%libdir%
    rm -rf $installdir/usr/share/doc
