name       : kstars
version    : 3.5.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/kstars/kstars-3.5.2.tar.xz : 897eeb3106dcb5d2b701e1f866f1fe4f8aefd591f09f9e6eac9875e742a85d75
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(libraw)
    - pkgconfig(Qt5DataVisualization)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kplotting-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/%libdir%
    rm -rf $installdir/usr/share/doc
