name       : kstars
version    : 3.5.8
release    : 26
source     :
    - https://cdn.download.kde.org/stable/kstars/kstars-3.5.8.tar.xz : 660d902837b7abf3810d6e24f72fd84f0444a29bd7d43e1896b19fece1c88c3f
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(libraw)
    - pkgconfig(Qt5DataVisualization)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kplotting-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/%libdir%
    rm -rf $installdir/usr/share/doc
