name       : kstars
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kstars-17.08.3.tar.xz : b6b1aad357548d293051380fc1ab2bf8dd8b397f5c31b8fe14dc72b2ac2e2644
license    : GPL-2.0
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kplotting-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
