name       : kstars
version    : 3.4.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/kstars/kstars-3.4.2.tar.xz : 1300c0a9ef46972c56bbf2cca238b2106b7b8e6160f29dd2f057c3fdd09045ef
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(libraw)
    - pkgconfig(Qt5DataVisualization)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kplotting-devel
    - kwindowsystem-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/%libdir%
    rm -rf $installdir/usr/share/doc
