name       : kstars
version    : 3.2.2
release    : 7
source     :
    - https://origin.download.kde.org/stable/kstars/kstars-3.2.2.tar.xz : a9351fb32d1497406779ea6210a672e13a9bde065869eb5776bb9c15d9c6c5fc
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kplotting-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
