name       : kstars
version    : 3.5.0
release    : 21
source     :
    - https://download.kde.org/stable/kstars/kstars-3.5.0.tar.xz : a1aa6e859b90bedcf88664c13e0cdfef6407aca1ee6eef608310d8a5caa9f33a
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(libraw)
    - pkgconfig(Qt5DataVisualization)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kplotting-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/%libdir%
    rm -rf $installdir/usr/share/doc
