name       : kstars
version    : 16.12.3
release    : 1
source     :
    - https://download.kde.org/stable/applications/16.12.3/src/kstars-16.12.3.tar.xz : 3eb054971d250be83edfc603c379854a5b5a1caf03bc66386005711bf2b19951
license    : GPL-2.0
component  : desktop
summary    : A Desktop Planetarium for KDE
description: |
    A Desktop Planetarium for KDE
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kplotting-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
